"use client";

import { useContext, useEffect } from "react";
import ScaffoldNetworkWholeGraph from "../../../components/tools/toolComp/ScaffoldNetworkWholeGraph";
import ScaffNetDets from "../../../components/tools/toolComp/ScaffNetDets";
import ScaffoldSettings from "../../../components/tools/toolComp/ScaffoldSettings";
import TargetContext from "../../../context/TargetContext";
import { deserializeGraph, graph_molecule_image_generator } from "../../../components/utils/rdkit_loader";
import RDKitContext from "../../../context/RDKitContext";
import { Tabs } from "@mantine/core";
import ScaffoldNetworkTreeView from "../../../components/tools/toolComp/SteppedWholeGraph";

export default function DisplayGraph() {
  const { target } = useContext(TargetContext);
  const { rdkit } = useContext(RDKitContext);

  // useEffect(() => {
  //   if (target.scaffold_network != undefined) {
  //     setTimeout(() => {
  //       // Replace graphology with plain object
  //       const network_graph = deserializeGraph(target.scaffold_network);
  //       const image_graph = graph_molecule_image_generator(rdkit, network_graph);
  //     }, 100);
  //   }
  // }, []);

  return (
    <div className="tools-container">
      <h1>Scaffold Tree</h1>
      <details open={false}>
        <summary>How to interpret these results</summary>
          After generating the initial tree structure, the 'Tree View' or the 'Node View' can be selected to 
          understand the core chemical structures (scaffolds) of the dataset. Scaffolds are displayed where 
          '*' represents any atom and '--' represents any bond type. 
            <ul>
              <li>
                <b>Tree View</b> presents a hierarchical tree of scaffold or molecule cards. 
                Each card can be selected to reveal more specific substructure cards belonging to 
                the selected generalised scaffold structure. Eventually the increasingly specific 
                structures represent the individual molecules of the dataset.
              </li>
              <li>
                <b>Node View</b> presents the same tree structure data via a mathematical graph or network representation. Each
                general scaffold can be selected to view it as a central node connecting to neighbouring nodes. The 
                neighbouring nodes are the immediate, more specific substructures. 
              </li>
            </ul> 
      </details>
      <details open={false}>
        <summary>How is the scaffold tree generated?</summary>
          <p>
          Scaffold trees and scaffold networks are generated by applying rules which systematically simplify molecules into their more 
          general forms. These rules were originally introduced by&nbsp;<a href = "https://doi.org/10.1021/ci2000924">Varin et al (2011)</a>.
          QITB uses an efficient implementation of these rules in RDKit, developed by &nbsp;<a href = "https://doi.org/10.1021/acs.jcim.0c00296">Krüger et al (2020)</a>.
          </p>
      </details>
      <Tabs defaultValue="Network_Settings">
        <Tabs.List>
          <Tabs.Tab value="Network_Settings">
            Tree Generation Settings
          </Tabs.Tab>
          <Tabs.Tab value="Whole_Network">
            Tree View
          </Tabs.Tab>
          <Tabs.Tab value="Network_Details" >
            Node View
          </Tabs.Tab>

        </Tabs.List>

        <Tabs.Panel value="Network_Settings">
          <ScaffoldSettings
          />
        </Tabs.Panel>

        {target.scaffold_network != undefined &&
          <>
            <Tabs.Panel value="Network_Details">
              <ScaffNetDets />
            </Tabs.Panel>

            <Tabs.Panel value="Whole_Network">
              <ScaffoldNetworkTreeView imageSize={200} />
            </Tabs.Panel>
          </>
        }
      </Tabs>
    </div >
  );
}
